name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

env:
  IMAGE_NAME: kubedeploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run tests
        env:
          CI_VERSION: ${{ github.ref }}
        run: sbt "; test; assembly"

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME" --label "runnumber=${GITHUB_RUN_ID}"